# Generated by Django 5.2.1 on 2025-05-09 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField()),
                ('probability', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age', models.FloatField()),
                ('resting_bp', models.FloatField()),
                ('cholestoral', models.FloatField()),
                ('max_heart_rate', models.FloatField()),
                ('oldpeak', models.FloatField()),
                ('fasting_blood_sugar', models.BooleanField()),
                ('rest_ecg', models.CharField(max_length=20)),
                ('exercise_angina', models.BooleanField()),
                ('slope', models.CharField(max_length=20)),
                ('vessels_colored', models.CharField(max_length=20)),
                ('thalassemia', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
